Document: rrun
Title: Debian rrun Manual
Author: <insert document author here>
Abstract: This manual describes what rrun is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rrun/rrun.sgml.gz

Format: postscript
Files: /usr/share/doc/rrun/rrun.ps.gz

Format: text
Files: /usr/share/doc/rrun/rrun.text.gz

Format: HTML
Index: /usr/share/doc/rrun/html/index.html
Files: /usr/share/doc/rrun/html/*.html
